executionInputs: []
triggers: []
steps:
  - params:
      - name: path
        value: ''
        code: false
    type: clone
    id: clone1
    displayName: Clone Git Repo
    description: iee
    timeout: null
    agent: null
    retries: null
    nextStep: null
kaholoVersion: 6.2.0
firstStep: clone1
